import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import sanityClient from "../sanityClient.js";

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sanity + Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {/* <pre>{JSON.stringify(posts, null, 2)}</pre> */}

      <main className={styles.main}>
        <h1 className={styles.title}>Read My Blog</h1>
        {posts.map((post) => {
          return (
            <article key={post._id}>
              <h2>
                <Link href={`/blog/${post.slug}`}>
                  <a>{post.title}</a>
                </Link>
              </h2>
              {/* <p>By {post.author}</p> */}
              {/* <p>{post.body}</p> */}
            </article>
          );
        })}
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const posts = await sanityClient.fetch(`*[_type == 'post']{'slug': slug.current, title, _id}`);
  return {
    props: {
      posts,
    },
  };
}
